# Web UI Server (ALWAYS active)
server:
  port: ${WEB_UI_PORT:9090}
  shutdown: graceful

spring:
  application:
    name: mcp-bsl-server
  lifecycle:
    timeout-per-shutdown-phase: 30s
  # CORS configuration
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600

# Logging configuration
logging:
  level:
    root: INFO
    com.github.steel33ff.mcpbsl: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  loki:
    enabled: ${LOGGING_ENABLED:true}
    url: ${LOKI_URL:http://localhost:3100/loki/api/v1/push}

# Management endpoints (Actuator) - on Web UI port
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# Swagger/OpenAPI - on Web UI port
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
    enabled: true
    display-request-duration: true
    tags-sorter: alpha
    doc-expansion: none
    operations-sorter: alpha

# MCP Transport configuration
mcp:
  transport: ${MCP_TRANSPORT:stdio}  # Options: stdio, http, sse, ndjson
  port: ${MCP_PORT:8080}             # Only for http/sse/ndjson modes
  
# BSL Language Server configuration
bsl:
  jar-path: ${BSL_JAR_PATH:/opt/bsl/bsl-language-server.jar}
  jvm:
    max-heap: ${BSL_MAX_HEAP:4g}
  pool:
    max-size: ${BSL_POOL_MAX_SIZE:5}
    ttl-minutes: ${BSL_POOL_TTL:60}

# Path mapping (Docker volume)
path:
  mount:
    host-root: ${MOUNT_HOST_ROOT:}
    container-root: /workspaces

